version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: blog-postgres
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - blog_postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network
    restart: unless-stopped

volumes:
  blog_postgres_data:
    driver: local

networks:
  blog-network:
    driver: bridge